// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type List struct {
	ID          interface{}
	Name        string
	Description sql.NullString
}
